listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/aclfile
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
persistence false
sys_interval 1
