db_server:
  ip: localhost
  port: 5432
  connection:
    user: postgres
    pw: postgres
  database:
    db_language: postgresql
    db_adapter: psycopg2
    db_schema: staging
    db_name: mqtt
      db_comment: 'This comment explain what the data is used for, that it is a staging-area which means the data is not ready to work with and you have 2 do datascience-stuff!'
    db_tables: 
      cluster1:
        tbl_name: tbl_staging_mqtt
        tbl_comment: 'comment about the first group of topics, which adds some more insights to the data for the datascientist'
      cluster2:
        tbl_name: tbl4cluster2
        tbl_comment: 'comment about the second group of topics, which adds some more insights to the data for the datascientist'

mqtt_server:
  ip: '127.0.0.1'
  port: 1883
  connection:
    user: admin
    pw: password
  topics:
    cluster1:
      - $SYS/broker/#
      - this/could/be/another/topic/#
    cluster2:
      - thats/the/third/topic/#
      - aaand/another/one
