db_server:
  ip: localhost
  port: 5432
  connection:
    user: postgres
    pw: postgres
  database:
    db_language: postgresql
    db_adapter: psycopg2
    db_name: staging_mqtt
    db_table: tbl_staging_mqtt

mqtt_server:
  ip: '127.0.0.1'
  port: 1883
  connection:
    user: admin
    pw: password
  topics:
    - $SYS/broker/#
    - this/could/be/another/topic/#
    - thats/the/third/topic/#
    - aaand/another/one