db_server:
  ip: localhost
  port: 5432
  connection:
    user: postgres
    pw: postgres
  database:
    db_language: postgresql
    db_adapter: psycopg2
    db_name: pg_database
    db_table: pg_table

mqtt_server:
  ip: '127.0.0.1'
  port: 1883
  connection:
    user: admin
    pw: password
  topics:
    - $SYS/broker/#